[package]
name = "startpage-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
diesel = { version = "2.1.4", features = ["mysql"] }
dotenvy = "0.15.7"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
sqlx = { version = "0.7", features = [ "runtime-tokio", "tls-native-tls", "mysql" ] }

[[bin]]
name = "server"

[lib]
name = "startpage"
path = "src/lib.rs"


default-run = "server"

